#!/bin/bash

# This core library contains logic related to the IMVIP download server
# which serves software packages for the IMVIP mobile application.
#
# @author cyril
# @since 0.1.0


#
# This function returns the proper client name. For unrecognized clients,
# an empty string will be returned and an return code of 0 will be 
# returned.
#
# @param $1 the client name
# @return 0 if function is called without error, else otherwise.
#
function imvip_get_client() {
	
	case "$1" in
		"and")
			echo "android"
		;;

		"iph")
			echo "iphone"
		;;

		*)
			echo ""
		;;
	esac

}
