#!/bin/sh
# postinst script for imvipdlsvr
#
# see: dh_installdeb(1)

# to make the installation failed immeidately in case of any unexpected error.
set -e


# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package.


##
## Main routine.
##
case "$1" in
	configure)

	#
	# create directories if not exists
	#

	# configuration directory @ /etc
	if [ ! -d /etc/imvipdlsvr ]; then
		install -d -m755 /etc/imvipdlsvr
	fi

	# variable data
	if [ ! -d /var/lib/imvipdlsvr ]; then
		install -d -m775 /var/lib/imvipdlsvr
	fi
	ln -sf /var/lib/imvipdlsvr /usr/share/imvipdlsvr/data
	#
	if [ ! -d /var/lib/imvipdlsvr/data/built_pkg ]; then
		install -d -m775 -o www-data -g www-data /var/lib/imvipdlsvr/built_pkg
	fi
	if [ ! -d /var/lib/imvipdlsvr/data/src_pkg ]; then
		install -d -m775 -o www-data -g www-data /var/lib/imvipdlsvr/src_pkg
	fi
	if [ ! -d /var/lib/imvipdlsvr/data/latest_pkg ]; then
		install -d -m775 -o www-data -g www-data /var/lib/imvipdlsvr/latest_pkg
	fi
	# log directory
	if [ ! -d /var/log/imvipdlsvr ]; then
		install -d -m775 -o www-data -g www-data /var/log/imvipdlsvr
	fi
	ln -sf /var/log/imvipdlsvr /usr/share/imvipdlsvr/log
	# conf


	#
	# fix links under the /usr/share/imvipdlsvr/ directory
	#
	ln -sf /etc/imvipdlsvr /usr/share/imvipdlsvr/conf
	

	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac


# completed successfully.
exit 0
